services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-master
    user: root
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    networks:
      - fastpick-infra

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - fastpick-infra

networks:
  fastpick-infra:
    driver: bridge

volumes:
  jenkins_data:
